### ISSUE TITLE
Any plan to update or maintain it?

### ISSUE THREAD

**Issue by ghost** [oseiskar/docker-vpn-browser#3]
Hello, Is there any plan to maintain it? it seems like great idea. 
I found 2 project with both are missing something may be if possible to combine it? 
https://github.com/jlesage/docker-firefox
https://github.com/haugene/docker-transmission-openvpn
Thanks

**Comment by oseiskar** [comment]
Hello. I am maintaining this project by updating it from time to time in case the current features stop working due to, e.g., Firefox updates. However, I'm not actively adding any new features. If you feel something is missing that you would be willing to add yourself, feel welcome to submit a Pull Request.

Note that Firefox, OpenVPN and Transmission are already included in this project
